version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@2.0.1
  gh: circleci/github-cli@2.7.0

jobs:
  gatekeeper-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh/setup
      - run:
          name: Check PR conditions before proceeding
          command: |
            # 获取PR是否来自Fork的信息。--jq 是 gh cli 的推荐用法
            IS_FORKED_PR=$(gh pr view << pipeline.event.github.pull_request.number >> --json isCrossRepository --jq.isCrossRepository)

            # 检查是否是内部成员的PR (isCrossRepository 的值为 false)
            if; then
              echo "This is a member PR. Proceeding with the build."
              exit 0
            # 否则，这就是一个来自Fork的PR
            else
              echo "This is a forked PR. Checking for 'run-ci' label..."
              # 直接在if条件中检查 'run-ci' 标签是否存在
              # gh pr view... | grep -q... 如果找到匹配项，命令会成功(退出码为0)
              if gh pr view << pipeline.event.github.pull_request.number >> --json labels --jq '.labels.name' | grep -q '^run-ci$'; then
                echo "Forked PR has the 'run-ci' label. Proceeding with the build."
                exit 0
              else
                echo "Forked PR does not have the 'run-ci' label. Halting workflow."
                circleci-agent step halt
              fi
            fi

workflows:
  setup:
    jobs:
      - gatekeeper-job:
          context: github-creds
      - path-filtering/filter:
          name: check-paths
          requires:
            - gatekeeper-job
          mapping: .circleci/path-filtering/pipeline_parameters.txt
          base-revision: main
          config-path: .circleci/continue_config.yml
