version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@2.0.1
  gh: circleci/github-cli@2.7.0

gatekeeper-job:
    docker:
      - image: cimg/base:stable
    steps:
      - gh/setup
      - run:
          name: Check PR conditions before proceeding
          command: |
            IS_FORKED_PR=$(gh pr view << pipeline.event.github.pull_request.number >> --json isCrossRepository -q.isCrossRepository)

            if; then
              echo "This is a member PR. Proceeding with the build."
              exit 0
            fi

            if; then
              echo "This is a forked PR. Checking for 'run-ci' label..."
              gh pr view << pipeline.event.github.pull_request.number >> --json labels -q '.labels.name' | grep -q '^run-ci$'

              if [ $? -eq 0 ]; then
                echo "Forked PR has the 'run-ci' label. Proceeding with the build."
                exit 0
              else
                echo "Forked PR does not have the 'run-ci' label. Halting workflow."
                circleci-agent step halt
              fi
            fi

workflows:
  setup:
    jobs:
      - gatekeeper-job:
          context: github-creds
      - path-filtering/filter:
          name: check-paths
          requires:
            - gatekeeper-job
          mapping: .circleci/path-filtering/pipeline_parameters.txt
          base-revision: main
          config-path: .circleci/continue_config.yml
