version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@2.0.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

workflows:
  setup:
    when:
      and:
        - not: << pipeline.parameters.enable_regtest >>
        - not: << pipeline.parameters.GHA_Action >>
        - not: << pipeline.parameters.GHA_Meta >>
        - not: << pipeline.parameters.GHA_Event >>
    jobs:
      - path-filtering/filter:
          name: check-paths
          mapping: .circleci/path-filtering/pipeline_parameters.txt
          base-revision: main
          config-path: .circleci/continue_config.yml
