version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@2.0.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  print-params:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print GHA Parameters
          command: |
            echo "Pipeline triggered by GHA."
            echo "GHA_Actor: << pipeline.parameters.GHA_Actor >>"
            echo "GHA_Event: << pipeline.parameters.GHA_Event >>"
            echo "GHA_Action: << pipeline.parameters.GHA_Action >>"
            echo "GHA_Meta: << pipeline.parameters.GHA_Meta >>"

workflows:
  debug-workflow:
    when: << pipeline.parameters.GHA_Actor >>
    jobs:
      - print-params

  setup:
    when:
      equal: [ "run-unit-test", << pipeline.parameters.GHA_Meta >> ]
    jobs:
      - path-filtering/filter:
          name: check-paths
          mapping: .circleci/path-filtering/pipeline_parameters.txt
          base-revision: main
          config-path: .circleci/continue_config.yml
