version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.5

parameters:
  run_go_test:
    type: boolean
    default: false

jobs:
  go_test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Run Go tests and generate coverage report
          command: go test -v -cover -race -coverprofile=coverage.out ./...
      - coveralls/upload:
          coverage_file: coverage.out
          coverage_format: golang
          flag_name: "go-tests"

  python_test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: pip install -r python_code/requirements.txt
      - run:
          name: Run Python tests and generate coverage report
          command: pytest --cov=python_code --cov-report=xml:coverage.xml python_code/
      - coveralls/upload:
          parallel: true
          coverage_file: coverage.xml
          coverage_format: cobertura
          flag_name: "python-tests"

  notify_coveralls_finished:
    docker:
      - image: cimg/base:stable
    steps:
      - coveralls/upload:
          parallel_finished: true
          flag_name: "all-tests"

workflows:
  test:
    when: << pipeline.parameters.run_go_test >>
    jobs:
      - go_test
      - python_test
      - notify_coveralls_finished:
          requires:
            - go_test
            - python_test