version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.5

parameters:
  run_go_test:
    type: boolean
    default: false

jobs:
  go_test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Run Go tests and generate coverage report
          command: go test -v -cover -race -coverprofile=coverage.out ./...
      - coveralls/upload:
          coverage_file: coverage.out
          coverage_format: golang
          flag_name: "go unit tests"

workflows:
  test:
    when: << pipeline.parameters.run_go_test >>
    jobs:
      - go_test
