name: 'Auto-approve and label member PRs'

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check author association and add label
        if: |
          github.event.pull_request.author_association == 'MEMBER' ||
          github.event.pull_request.author_association == 'OWNER' ||
          github.event.pull_request.author_association == 'COLLABORATOR'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const label = 'safe-to-test';

            console.log(`PR author is a member. Adding '${label}' label to PR #${prNumber}.`);

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: [label]
            });