name: Trigger CircleCI Coverage Test

on:
  pull_request_target:
    types: [labeled] # Only run when a label is added

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    # This job only runs if the label that was just added is exactly "run-ci-cov".
    if: github.event.label.name == 'run-ci-cov'
    steps:
      - name: Trigger CircleCI Pipeline
        run: |
          echo "Label 'run-ci-cov' was added to PR #${{ github.event.pull_request.number }}. Triggering CircleCI pipeline..."
          
          # We use curl to directly call the CircleCI API v2.
          # This is more flexible than the official trigger action.
          curl -X POST \
            --url "https://circleci.com/api/v2/project/gh/Song-Quan/circleci/pipeline/run" \
            --header "Content-Type: application/json" \
            --header "Circle-Token: ${{ secrets.CIRCLECI_API_TOKEN }}" \
            --data '{"definition_id":"219c1179-8254-4f27-8da2-1c3374e28029","config":{"branch":"main"},"checkout":{"branch":"pull/${{ github.event.pull_request.number }}/head"}}'